.PHONY: all cleansub
all:
	mkpsxiso -y ./isoconfig.xml
cleansub:
	$(MAKE) clean
	rm -f fnaf2.cue fnaf2.bin

TARGET = fnaf2

SRCS = fnaf2.c \
tim/office/oLEFTpart2.tim \
tim/office/oLEFTpart2light.tim \
tim/office/officeMIDDLE.tim \
tim/office/officeMIDDLElight.tim \
tim/office/oRIGHTpart2.tim \
tim/office/oRIGHTpart2light.tim \
tim/office/fan1.tim \
tim/office/fan2.tim \
tim/office/fan3.tim \
tim/office/fan4.tim \
tim/office/officeFREDDY.tim \
tim/office/officeBONNIE.tim \
tim/office/officeCHICA.tim \
tim/office/officeTOYFREDDY.tim \
tim/office/officeTOYBONNIE.tim \
tim/office/mutecall.tim \
tim/office/manglehanging.tim \
tim/hallway/toychicahallway.tim \
tim/hallway/foxyhallway.tim \
tim/hallway/freddyhallway.tim \
tim/hallway/toyfreddyhallway.tim \
tim/hallway/bonniehallway.tim \
tim/hallway/goldenhallway.tim \
tim/hallway/foxanglhallway.tim \
tim/hallway/foxbonnhallway.tim \
tim/hallway/manglehallway.tim \
tim/screamer/jumpC.tim \
tim/screamer/jumpC2.tim \
tim/screamer/jumpC3.tim \
tim/screamer/jumpB.tim \
tim/screamer/jumpB2.tim \
tim/screamer/jumpB3.tim \
tim/screamer/jumpB4.tim \
tim/screamer/jumpB5.tim \
tim/screamer/jumpF0.tim \
tim/screamer/jumpF1.tim \
tim/screamer/jumpF2.tim \
tim/screamer/jumpF3.tim \
tim/screamer/jumpF4.tim \
tim/screamer/jumpF5.tim \
tim/screamer/jumpP1.tim \
tim/screamer/jumpP2.tim \
tim/screamer/jumpP3.tim \
tim/screamer/jumpP4.tim \
tim/screamer/jumpP5.tim \
tim/screamer/TBjump1.tim \
tim/screamer/TBjump2.tim \
tim/screamer/TBjump3.tim \
tim/screamer/TBjump4.tim \
tim/screamer/TBjump5.tim \
tim/screamer/TCjump1.tim \
tim/screamer/TCjump2.tim \
tim/screamer/TCjump3.tim \
tim/screamer/TCjump4.tim \
tim/screamer/Cjump1.tim \
tim/screamer/Cjump2.tim \
tim/screamer/Cjump3.tim \
tim/screamer/Cjump4.tim \
tim/screamer/Cjump5.tim \
tim/screamer/Mjump1.tim \
tim/screamer/Mjump2.tim \
tim/screamer/Mjump3.tim \
tim/screamer/Mjump4.tim \
tim/screamer/Mjump5.tim \
tim/screamer/jumpTF1.tim \
tim/screamer/jumpTF2.tim \
tim/screamer/jumpTF3.tim \
tim/screamer/jumpTF4.tim \
tim/screamer/jumpTF5.tim \
tim/screamer/jumpFO.tim \
tim/screamer/jumpFO2.tim \
tim/screamer/jumpFO3.tim \
tim/screamer/jumpFO4.tim \
tim/screamer/jumpFO5.tim \
tim/screamer/jumpGF.tim \
tim/timer/timer0.tim \
tim/timer/timer1.tim \
tim/timer/timer2.tim \
tim/timer/timer3.tim \
tim/timer/timer4.tim \
tim/timer/timer5.tim \
tim/timer/timer6.tim \
tim/timer/timer7.tim \
tim/timer/timer8.tim \
tim/timer/timer9.tim \
tim/timer/timer10.tim \
tim/timer/timer11.tim \
tim/timer/timer12.tim \
tim/timer/timer13.tim \
tim/timer/timer14.tim \
tim/timer/timer15.tim \
tim/timer/timer16.tim \
tim/timer/timer17.tim \
tim/timer/timer18.tim \
tim/timer/timer19.tim \
tim/timer/timer20.tim \
tim/5am6/SAM.tim \
tim/5am6/FAM.tim \
tim/5am6/5AM1.tim \
tim/5am6/5AM2.tim \
tim/5am6/5AM3.tim \
tim/5am6/5AM4.tim \
tim/5am6/5AM5.tim \
tim/5am6/6AM1.tim \
tim/5am6/6AM2.tim \
tim/5am6/6AM3.tim \
tim/5am6/6AM4.tim \
tim/5am6/6AM5.tim \
tim/5am6/6AM6.tim \
tim/load.tim \
tim/fnt.tim \
tim/GJSIX.tim \
tim/static1.tim \
tim/itsme.tim \
tim/gameover.tim \
tim/danger1.tim \
tim/danger2.tim \
vag/light.vag \
vag/monitor_down.vag \
vag/monitor_up.vag \
vag/mask-down.vag \
vag/mask-up.vag \
vag/officesound.vag \
vag/click.vag \
vag/screamer.vag \
vag/honk.vag \
vag/jamlight.vag \
vag/coin.vag \
vag/vent1.vag \
vag/vent2.vag \
vag/alarm.vag \
vag/windup.vag \
vag/BB1.vag \
vag/BB2.vag \
vag/BB3.vag \
vag/clickfail.vag \

include ../common.mk 
