.PHONY: all cleansub
all:
	mkpsxiso -y ./isoconfig.xml
cleansub:
	$(MAKE) clean
	rm -f fnaf2.cue fnaf2.bin

TARGET = fnaf2

SRCS = fnaf2.c \
tim/oLEFTpart2.tim \
tim/oLEFTpart2light.tim \
tim/officeLEFTlighttoychica.tim \
tim/officeMIDDLE.tim \
tim/officeMIDDLElight.tim \
tim/oRIGHTpart2.tim \
tim/oRIGHTpart2light.tim \
tim/officeRIGHTlighttoybonnie.tim \
tim/officeRIGHTlightmangle.tim \
tim/CAMERAMONITOR.tim \
tim/FAM.tim \
tim/load.tim \
tim/SAM.tim \
tim/fnt.tim \
tim/GJFIV.tim \
tim/GJSEV.tim \
tim/GJSIX.tim \
tim/jumpC.tim \
tim/jumpC2.tim \
tim/jumpC3.tim \
tim/jumpB.tim \
tim/jumpB2.tim \
tim/jumpB3.tim \
tim/jumpB4.tim \
tim/jumpB5.tim \
tim/jumpF0.tim \
tim/jumpF1.tim \
tim/jumpF2.tim \
tim/jumpF3.tim \
tim/jumpF4.tim \
tim/jumpF5.tim \
tim/jumpP1.tim \
tim/jumpP2.tim \
tim/jumpP3.tim \
tim/jumpP4.tim \
tim/jumpP5.tim \
tim/TBjump1.tim \
tim/TBjump2.tim \
tim/TBjump3.tim \
tim/TBjump4.tim \
tim/TBjump5.tim \
tim/jumpTF1.tim \
tim/jumpTF2.tim \
tim/jumpTF3.tim \
tim/jumpTF4.tim \
tim/jumpTF5.tim \
tim/jumpFO.tim \
tim/jumpFO2.tim \
tim/jumpFO3.tim \
tim/jumpFO4.tim \
tim/jumpFO5.tim \
tim/static1.tim \
tim/5AM1.tim \
tim/5AM2.tim \
tim/5AM3.tim \
tim/5AM4.tim \
tim/5AM5.tim \
tim/6AM1.tim \
tim/6AM2.tim \
tim/6AM3.tim \
tim/6AM4.tim \
tim/6AM5.tim \
tim/6AM6.tim \
tim/itsme.tim \
tim/fan1.tim \
tim/fan2.tim \
tim/fan3.tim \
tim/fan4.tim \
tim/timer0.tim \
tim/timer1.tim \
tim/timer2.tim \
tim/timer3.tim \
tim/timer4.tim \
tim/timer5.tim \
tim/timer6.tim \
tim/timer7.tim \
tim/timer8.tim \
tim/timer9.tim \
tim/timer10.tim \
tim/timer11.tim \
tim/timer12.tim \
tim/timer13.tim \
tim/timer14.tim \
tim/timer15.tim \
tim/timer16.tim \
tim/timer17.tim \
tim/timer18.tim \
tim/timer19.tim \
tim/timer20.tim \
tim/gameover.tim \
tim/toychicahallway.tim \
tim/foxyhallway.tim \
tim/freddyhallway.tim \
tim/toyfreddyhallway.tim \
tim/bonniehallway.tim \
tim/officeFREDDY.tim \
tim/officeBONNIE.tim \
tim/officeCHICA.tim \
tim/officeTOYFREDDY.tim \
tim/officeTOYBONNIE.tim \
tim/mutecall.tim \
tim/manglehanging.tim \
vag/light.vag \
vag/monitor_down.vag \
vag/monitor_up.vag \
vag/mask-down.vag \
vag/mask-up.vag \
vag/officesound.vag \
vag/click.vag \
vag/screamer.vag \
vag/honk.vag \
vag/jamlight.vag \
vag/coin.vag \
vag/vent1.vag \
vag/vent2.vag \
vag/alarm.vag \
vag/windup.vag \
vag/BB1.vag \
vag/BB2.vag \
vag/BB3.vag \
vag/clickfail.vag \

include ../common.mk 
